# Use an official Node.js runtime as base image
FROM node:14

# Set the working directory in docker
WORKDIR /frontend

# Copy the package.json and package-lock.json
COPY frontend/package*.json ./

# Install any dependencies
RUN npm install

# Copy the content of the local src directory to the working directory
COPY frontend /frontend

# Start the React app
CMD ["npm", "start"]
