# fly.toml app configuration file generated for ashwin-rachha on 2023-08-30T01:39:56-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ashwin-rachha"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
